# Generated by Django 2.1.1 on 2018-12-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id_agent', models.IntegerField(primary_key=True, serialize=False)),
                ('sys_name', models.TextField(max_length=255)),
                ('version', models.TextField(max_length=255)),
                ('arch', models.TextField(max_length=255)),
                ('os_name', models.TextField(max_length=255)),
                ('os_version', models.TextField(max_length=255)),
            ],
        ),
    ]
