# Generated by Django 2.1.1 on 2018-12-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='arch',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='os_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='os_version',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='sys_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='version',
            field=models.CharField(max_length=255),
        ),
    ]
