# Generated by Django 2.0.6 on 2018-09-10 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Host Name')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='Ip Address')),
                ('port', models.CharField(max_length=10, verbose_name='Port SSH')),
                ('os', models.CharField(max_length=200, verbose_name='Operating System')),
                ('num_of_inst', models.IntegerField(default=0, verbose_name='Number of Instance')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Instance Name')),
                ('db_name', models.CharField(max_length=200, verbose_name='Database Name')),
                ('domain', models.CharField(max_length=200, verbose_name='Domain Name')),
                ('usr_deployed', models.CharField(blank=True, max_length=200, verbose_name='User Deployed')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('latest_deploy', models.DateTimeField(auto_now_add=True, verbose_name='Latest Deploy')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Project Name')),
                ('url', models.TextField(verbose_name='Remote URL')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Project Version')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Project')),
            ],
        ),
        migrations.AddField(
            model_name='instance',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Project'),
        ),
        migrations.AddField(
            model_name='instance',
            name='project_ver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Version'),
        ),
    ]
