# Generated by Django 2.1.2 on 2018-10-13 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manager.Project'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='project_ver',
            field=models.ForeignKey(db_column='project', on_delete=django.db.models.deletion.CASCADE, to='manager.Version', to_field='project'),
        ),
        migrations.AlterField(
            model_name='version',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Project', unique=True),
        ),
    ]
