# Generated by Django 2.1.2 on 2018-10-13 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20181013_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='project_ver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Version'),
        ),
        migrations.AlterField(
            model_name='version',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Project'),
        ),
    ]
